kind: pipeline
type: digitalocean
name: A
token:
  from_secret: token
server:
  image: docker-18-04
  size: s-1vcpu-1gb
  region: lon1
steps:
- name: greeting
  commands:
  - echo hello world
---
kind: pipeline
type: digitalocean
name: B
token:
  from_secret: token
server:
  image: docker-18-04
  size: s-1vcpu-1gb
  region: lon1
steps:
- name: greeting
  commands:
  - echo hello world
---
kind: pipeline
type: digitalocean
name: Done 
token:
  from_secret: token
server:
  image: docker-18-04
  size: s-1vcpu-1gb
  region: lon1
steps:
- name: greeting
  commands:
  - echo all done
depends_on:
- A
- B
